---
title: "Real and toy data un-segmented bootstrap ranges"
author: "Michael Love"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output:
  rmarkdown::html_document:
    highlight: tango
vignette: |
  %\VignetteIndexEntry{Toy data bootstrap ranges}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(AnnotationHub)
ah <- AnnotationHub()
pks <- query(ah, c("DnaseSeq", "narrowPeak", "A549", "UniPk"))[[1]]
```

```{r}
library(GenomeInfoDb)
pks <- keepStandardChromosomes(pks)
seqlevels(pks) <- setdiff(seqlevels(pks), "chrM")
table(seqnames(pks))
pks <- sort(pks)
```

```{r}
library(nullranges)
```

Evaluate times:

```{r}
library(microbenchmark)
microbenchmark(list=alist(
                 p_within=bootstrap_granges(pks, L_b=5e5, type="permute"),
                 b_within=bootstrap_granges(pks, L_b=5e5),
                 p_across=bootstrap_granges(pks, L_b=5e5, within_chrom=FALSE, type="permute"),
                 b_across=bootstrap_granges(pks, L_b=5e5, within_chrom=FALSE)
), times=10)
```

# Visualize boot on synthetic data

```{r}
library(GenomicRanges)
gr <- GRanges(rep(c("chr1","chr2","chr3"),c(4,5,2)),
              IRanges(start=c(1,101,121,201,101,201,216,231,401,1 ,101),
                      width=c(20, 5,  5, 30, 20,  5,  5,  5, 30,80,80)),
              seqlengths=c(chr1=300,chr2=450,chr3=200))
```

```{r}
library(ggbio)
ggbio::autoplot(gr)
```

```{r}
library(BentoBox)
library(TxDb.Hsapiens.UCSC.hg19.knownGene)

## Define function for plotting GRanges with BentoBox
plotGRanges <- function(gr) {
  
  ## Shared parameters
  p <- bb_params(chromstart = 0, chromend = 500,
                 x = 0.5, width = 4, height = 0.5,
                 at = seq(0, 500, 50))
  
  ## Create page to contain plots
  bb_pageCreate(width = 5, height = 2, xgrid = 0, ygrid = 0, showGuides = F)
  
  ## Plot GRanges for each chromosome
  p1 <- bb_plotBed(data = gr, params = p, chrom = 'chr1',
                   y = 0.25, just = c('left', 'bottom'))
  bb_annoGenomeLabel(plot = p1, params = p, y = 0.30)
  
  p2 <- bb_plotBed(data = gr, params = p, chrom = 'chr2',
                   y = 1.0, just = c('left', 'bottom'))
  bb_annoGenomeLabel(plot = p2, params = p, y = 1.05)
  
  p3 <- bb_plotBed(data = gr, params = p, chrom = 'chr3',
                   y = 1.75, just = c('left', 'bottom'))
  bb_annoGenomeLabel(plot = p3, params = p, y = 1.80)

}

plotGRanges(gr)

```

```{r}
for (s in 1:5) {
  set.seed(s)
  gr_prime <- bootstrap_granges(gr, L_b=100, type="permute")
  plotGRanges(gr_prime)
}
```

```{r}
for (s in 1:5) {
  set.seed(s)
  gr_prime <- bootstrap_granges(gr, L_b=100)
  plotGRanges(gr_prime)
}
```

# Now across chroms:

Simple case, move fixed blocks around:

```{r}
for (s in 1:5) {
  set.seed(s)
  gr_prime <- bootstrap_granges(gr, L_b=200, type="permute", within_chrom=FALSE)
  plotGRanges(gr_prime)
}
```

Now, randomly placed blocks with replacement (default `type="bootstap"`):

```{r}
for (s in 1:5) {
  set.seed(s)
  gr_prime <- bootstrap_granges(gr, L_b=200, within_chrom=FALSE)
  plotGRanges(gr_prime)
}
```
