---
title: "Matching ranges"
author: "Eric S. Davis"
date: "`r format(Sys.Date(), '%m/%d/%Y')`"
output:
  rmarkdown::html_document:
    highlight: tango
    toc: true
    toc_float: true	
    fig_width: 5
    fig_height: 3
vignette: |
  %\VignetteIndexEntry{Matching ranges}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r}
library(nullranges)
library(magrittr)
```

Test data

```{r}
library(nullrangesData)
data("enhPromContactFreqHg19")
```

Define parameters

```{r}
set.seed(123)
s <- sample(1:length(enhPromContactFreqHg19), 6000)
x <- enhPromContactFreqHg19[head(s, 1000)]
u <- enhPromContactFreqHg19[tail(s, 5000)]
covar = ~ anchor1.peakStrength + contactFreq
```

Match GInteractions object

```{r}
mgi <- matchRanges(focal = x, pool = u, covar = covar,
                   method = 'nearest', replace = TRUE)
```

Prints and behaves like a normal GInteractions object

```{r}
mgi
```

Visualize matching

```{r vis-match, eval=FALSE}
# I get error: EXPR must be a length 1 vector...
plot(mgi) #plot shows propensity scores
plot(mgi, type = 'ridge')
plotCovariates(mgi, covar = 'all', type = 'ridge', logTransform = TRUE)
plotCovariates(mgi, covar = 'all', type = 'jitter', logTransform = TRUE)
plotCovariates(mgi, covar = 'contactFreq', type = 'jitter', logTransform = TRUE)
```

Summary and access data

```{r}
overview(mgi)
matchedData(mgi) %>% head()
covariates(mgi)
```

Get each type of result as GInteractions objects

```{r}
focal(mgi)
pool(mgi)
matched(mgi)
unmatched(mgi)
```

Extract indices by group (default is 'matched')

```{r}
indices(mgi, group = "unmatched") %>% head()
indices(mgi) %>% head()
```

Should be `TRUE`:

```{r}
identical(matchedData(mgi)[group == "pool"][indices(mgi, group = "unmatched"), -c('group')],
          matchedData(mgi)[group == "unmatched", -c('group')])
```
